version: "3"
services:
  test:
    container_name: frida-test
    image: ubuntu
    ports:
      - "23946:23946"
    networks:
      - vnet
    volumes:
      - ./example:/data
    tty: true
networks:
  vnet:
    driver: bridge